name: Generate podcast feeds
on:
  push:
    branches:
      - main  # or whatever branch you want to trigger this on

jobs:
  build: 
    runs-on: ubuntu-latest  # 'u' in 'ubuntu' should be lowercase
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with: 
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run feed Generator
        run: python feed.py

      - name: Push Changes
        run: |
          git config user.name "github actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Modified feed"
          git push

        
         
           
        
